---

name: "Library-Manager"
guid: "ee998539-7959-4afa-a88a-9755e315b839"
version: "0.0.0.1"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "Amatsu-Kami"
artifacts:
- "Jellyfin.Plugin.Library.Manager.dll"
changelog: >
  changelog
- name: jprm-build
  uses: oddstr13/jellyfin-plugin-repository-manager@v0.5.0