---

name: "Library-Manager"
guid: "ee998539-7959-4afa-a88a-9755e315b839"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "This plugin let's you manage your library."
description: >
  This plugin let's you change the library of the medias.
category: "General"
owner: "Amatsu-Kami"
artifacts:
- "Jellyfin.Plugin.Library.Manager.dll"